
name: publish

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildxname: Docker Image CI
2
​
3
on:
4
  push:
5
    branches: [ "main" ]
6
  pull_request:
7
    branches: [ "main" ]
8
​
9
jobs:
10
​
11
  build:
12
​
13
    runs-on: ubuntu-latest
14
​
15
    steps:
16
    - uses: actions/checkout@v3
17
    - name: Build the Docker image
18
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
19

        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push AMD64 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: sajiljoseph/nitter:latest,sajiljoseph/nitter:${{ github.sha }}
      - name: Build and push ARM64 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: sajiljoseph/nitter:latest-arm64,sajiljoseph/nitter:${{ github.sha }}-arm64
